# Generated by Django 4.1.3 on 2022-11-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='excerto',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
