# Generated by Django 4.1.3 on 2022-11-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_conteudo_post_excerto_post_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerto',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
