# Generated by Django 4.1.3 on 2022-11-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_conteudo_alter_post_excerto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
